### ISSUE TITLE
Cannot see it in Ardour

### ISSUE THREAD

**Issue by ghost** [x42/property_example.lv2#4]
I cannot search it in Ardour 5.12/ Debian 9. In Carla and QTractor(last version) I can search it.
The plugin has been installed at /usr/local/lib/lv2/

**Comment by x42** [comment]
That is a know bug in Ardour 5.12 - it does not show generic UI elements if there are no _normal_ control ports. This is already fixed in Ardour/git.

The controls are however available in automation-lanes and mixer-strip inline controls in 5.12

**Comment by x42** [comment]
re "Search" in Ardour it's under "utils" in the plugin-manager.

**Comment by ghost** [comment]
Thank you, I see it now. But can't see the controls because I need to update Ardour.

**Comment by x42** [comment]
..or use the inline or automation-controls:

![inline_and_automation_ctrls](https://user-images.githubusercontent.com/30246/50424356-c071a000-0862-11e9-9638-7f882a3d6eac.png)

In any case, it's an example and test plugin only.
